version: '3'

services:
  # Database
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "4406:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: scheduler
